# Data Cleaning of Fantasy Football Data from 2021

### Data downloaded from <a href= "https://fantasydata.com/">FantasyData</a>

### Import Libraries

In [15]:
# import libraries

import pandas as pd
import numpy as np
import sys
import requests
import matplotlib.pyplot as plt
import seaborn as sbn

### Clean Player Data

In [11]:
# load and view data
players = pd.read_csv("Player.2021.csv")
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4103 entries, 0 to 4102
Data columns (total 28 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PlayerID              4103 non-null   int64
 1   Team                  2486 non-null   object
 2   Number                2317 non-null   float64
 3   FirstName             4103 non-null   object
 4   LastName              4103 non-null   object
 5   Position              4103 non-null   object
 6   Status                4103 non-null   object
 7   Height                4103 non-null   object
 8   Weight                4103 non-null   int64
 9   BirthDate             4076 non-null   object
 10  College               4103 non-null   object
 11  Experience            4102 non-null   float64
 12  FantasyPosition       4103 non-null   object
 13  PositionCategory      4103 non-null   object
 14  PhotoUrl              4103 non-null   object
 15  ByeWeek               2486 non-null   float64
 16  AverageDraftPosition  2115 non-null   float64
 17  CollegeDraftTeam      4101 non-null   object
 18  CollegeDraftYear      4099 non-null   float64
 19  CollegeDraftRound     2178 non-null   float64
 20  CollegeDraftPick      2174 non-null   float64
 21  IsUndraftedFreeAgent  4101 non-null   object
 22  FanDuelPlayerID       1470 non-null   float64
 23  DraftKingsPlayerID    1639 non-null   float64
 24  InjuryStatus          539 non-null    object
 25  FanDuelName           1468 non-null   object
 26  DraftKingsName        1795 non-null   object
 27  TeamID                2486 non-null   float64
dtypes: float64(10), int64(2), object(16)
memory usage: 897.7+ KB

In [12]:
# replace NaN's with empty strings
players = players.replace(np.nan, '', regex=True)
players.head()

,PlayerID,Team,Number,FirstName,LastName,Position,Status,Height,Weight,BirthDate,...,CollegeDraftYear,CollegeDraftRound,CollegeDraftPick,IsUndraftedFreeAgent,FanDuelPlayerID,DraftKingsPlayerID,InjuryStatus,FanDuelName,DraftKingsName,TeamID
0,430,,,Sam,Koch,P,Inactive,"6'1""",222,8/13/1982 12:00:00 AM,...,2006.0,6.0,203.0,False,,,,,,
1,722,,,Jason,Witten,TE,Inactive,"6'6""",263,5/6/1982 12:00:00 AM,...,2003.0,3.0,69.0,False,6641.0,184571.0,,Jason Witten,Jason Witten,
2,1658,,,Greg,Olsen,TE,Inactive,"6'5""",255,3/11/1985 12:00:00 AM,...,2007.0,1.0,31.0,False,6914.0,230925.0,,Greg Olsen,Greg Olsen,
3,2982,,,Stephen,Gostkowski,K,Inactive,"6'1""",215,1/28/1984 12:00:00 AM,...,2006.0,4.0,118.0,False,7900.0,177862.0,,Stephen Gostkowski,Stephen Gostkowski,
4,3807,,,Ben,Roethlisberger,QB,Inactive,"6'5""",240,3/2/1982 12:00:00 AM,...,2004.0,1.0,11.0,False,6589.0,246061.0,,Ben Roethlisberger,Ben Roethlisberger,

In [24]:
# download player headshots 

for i in seq_len(nrow(players)): {
    download.file(url = players$PhotoUrl  [i], 
    destfile = paste0('files', players$FanDuelName[i], 
         '.png'), method = 'curl')
}

SyntaxError: invalid syntax (<ipython-input-24-513175e6f67e>, line 4)

In [22]:
url_list = list(players['PhotoUrl'])
name_list = list(players['FanDuelName'])

#headers = {
#    'Authorization': 'Bearer %s' %access_token,
#    'Accept-Encoding': 'gzip',
#}

result = list(zip(url_list,name_list))
for i,j in result:
    url_list ='PhotoUrl ' + i
    response = requests.get(url, headers=headers)
    print(response.status_code)
    original_stdout = sys.stdout
    
    with open(j, 'w') as f:
        sys.stdout = f
        print(response.text)
        sys.stdout = original_stdout

NameError: name 'url' is not defined